### ISSUE TITLE
Addon doesn't install emojione/monotone

### ISSUE THREAD

**Issue by jerdog** [kaakaa/slidev-addon-rabbit#3]
I have added this to my presentation with the `slidev-theme-the-unnamed` theme:

```yaml
addons:
  - slidev-addon-rabbit
rabbit:
  slideNum: true
```

When the presentation builds, these errors populate:

```
7:26:31 PM [vite] Pre-transform error: Icon `emojione-monotone/turtle` not found
7:26:31 PM [vite] Pre-transform error: Icon `emojione-monotone/flag-for-chequered-flag` not found
7:26:31 PM [vite] Pre-transform error: Icon `emojione-monotone/rabbit` not found
7:26:31 PM [vite] Internal server error: Icon `emojione-monotone/rabbit` not found
      at generateComponent (file:///Users/jerdog/dev/talks/streamlining-devex-slidev/node_modules/unplugin-icons/dist/chunk-BN55ESQF.js:358:11)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async LoadPluginContext.load (file:///Users/jerdog/dev/talks/streamlining-devex-slidev/node_modules/unplugin-icons/dist/chunk-BN55ESQF.js:417:20)
      at async PluginContainer.load (file:///Users/jerdog/dev/talks/streamlining-devex-slidev/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:48967:22)
      at async loadAndTransform (file:///Users/jerdog/dev/talks/streamlining-devex-slidev/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:51762:22)
      at async viteTransformMiddleware (file:///Users/jerdog/dev/talks/streamlining-devex-slidev/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:61776:24)
7:26:31 PM [vite] Internal server error: Icon `emojione-monotone/flag-for-chequered-flag` not found
      at generateComponent (file:///Users/jerdog/dev/talks/streamlining-devex-slidev/node_modules/unplugin-icons/dist/chunk-BN55ESQF.js:358:11)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async LoadPluginContext.load (file:///Users/jerdog/dev/talks/streamlining-devex-slidev/node_modules/unplugin-icons/dist/chunk-BN55ESQF.js:417:20)
      at async PluginContainer.load (file:///Users/jerdog/dev/talks/streamlining-devex-slidev/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:48967:22)
      at async loadAndTransform (file:///Users/jerdog/dev/talks/streamlining-devex-slidev/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:51762:22)
      at async viteTransformMiddleware (file:///Users/jerdog/dev/talks/streamlining-devex-slidev/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:61776:24)
7:26:31 PM [vite] Internal server error: Icon `emojione-monotone/turtle` not found
      at generateComponent (file:///Users/jerdog/dev/talks/streamlining-devex-slidev/node_modules/unplugin-icons/dist/chunk-BN55ESQF.js:358:11)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async LoadPluginContext.load (file:///Users/jerdog/dev/talks/streamlining-devex-slidev/node_modules/unplugin-icons/dist/chunk-BN55ESQF.js:417:20)
      at async PluginContainer.load (file:///Users/jerdog/dev/talks/streamlining-devex-slidev/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:48967:22)
      at async loadAndTransform (file:///Users/jerdog/dev/talks/streamlining-devex-slidev/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:51762:22)
      at async viteTransformMiddleware (file:///Users/jerdog/dev/talks/streamlining-devex-slidev/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:61776:24)
7:26:31 PM [vite] Internal server error: Icon `emojione-monotone/turtle` not found
      at generateComponent (file:///Users/jerdog/dev/talks/streamlining-devex-slidev/node_modules/unplugin-icons/dist/chunk-BN55ESQF.js:358:11)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async LoadPluginContext.load (file:///Users/jerdog/dev/talks/streamlining-devex-slidev/node_modules/unplugin-icons/dist/chunk-BN55ESQF.js:417:20)
      at async PluginContainer.load (file:///Users/jerdog/dev/talks/streamlining-devex-slidev/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:48967:22)
      at async loadAndTransform (file:///Users/jerdog/dev/talks/streamlining-devex-slidev/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:51762:22)
      at async viteTransformMiddleware (file:///Users/jerdog/dev/talks/streamlining-devex-slidev/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:61776:24) (x2)
7:26:31 PM [vite] Internal server error: Icon `emojione-monotone/rabbit` not found
      at generateComponent (file:///Users/jerdog/dev/talks/streamlining-devex-slidev/node_modules/unplugin-icons/dist/chunk-BN55ESQF.js:358:11)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async LoadPluginContext.load (file:///Users/jerdog/dev/talks/streamlining-devex-slidev/node_modules/unplugin-icons/dist/chunk-BN55ESQF.js:417:20)
      at async PluginContainer.load (file:///Users/jerdog/dev/talks/streamlining-devex-slidev/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:48967:22)
      at async loadAndTransform (file:///Users/jerdog/dev/talks/streamlining-devex-slidev/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:51762:22)
      at async viteTransformMiddleware (file:///Users/jerdog/dev/talks/streamlining-devex-slidev/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:61776:24)
7:26:31 PM [vite] Internal server error: Icon `emojione-monotone/flag-for-chequered-flag` not found
      at generateComponent (file:///Users/jerdog/dev/talks/streamlining-devex-slidev/node_modules/unplugin-icons/dist/chunk-BN55ESQF.js:358:11)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async LoadPluginContext.load (file:///Users/jerdog/dev/talks/streamlining-devex-slidev/node_modules/unplugin-icons/dist/chunk-BN55ESQF.js:417:20)
      at async PluginContainer.load (file:///Users/jerdog/dev/talks/streamlining-devex-slidev/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:48967:22)
      at async loadAndTransform (file:///Users/jerdog/dev/talks/streamlining-devex-slidev/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:51762:22)
      at async viteTransformMiddleware (file:///Users/jerdog/dev/talks/streamlining-devex-slidev/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:61776:24)
```

The `package-lock.json` file has the modules:

```json
    "node_modules/slidev-addon-rabbit": {
      "version": "0.3.0",
      "resolved": "https://registry.npmjs.org/slidev-addon-rabbit/-/slidev-addon-rabbit-0.3.0.tgz",
      "integrity": "sha512-6tswki7erOWMNRCD9+Mg9usiPJlFbDCMTlV+SY+aVLQlUYkr058axwVrNCdYvHL5TZvb8p85fpnsENXfSC5NeA==",
      "license": "MIT",
      "dependencies": {
        "@slidev/theme-default": "^0.21.2"
      },
      "engines": {
        "node": ">=18.0.0",
        "npm": ">=9.5.0"
      }
    },
    "node_modules/slidev-addon-rabbit/node_modules/@slidev/theme-default": {
      "version": "0.21.2",
      "resolved": "https://registry.npmjs.org/@slidev/theme-default/-/theme-default-0.21.2.tgz",
      "integrity": "sha512-neUucFs2YrRZZd73QwvLTyRG/o1nerDFUR5t8YAmXVLTMzWfY71flQ6aAhjYf+WjsozYsOHcxi/pZtIzZ4VhTQ==",
      "license": "MIT",
      "dependencies": {
        "@slidev/types": "^0.22.7",
        "codemirror-theme-vars": "^0.1.1",
        "prism-theme-vars": "^0.2.2",
        "theme-vitesse": "^0.1.12"
      },
      "engines": {
        "node": ">=14.0.0",
        "slidev": ">=0.19.2"
      },
      "funding": {
        "url": "https://github.com/sponsors/antfu"
      }
    },
    "node_modules/slidev-addon-rabbit/node_modules/@slidev/types": {
      "version": "0.22.7",
      "resolved": "https://registry.npmjs.org/@slidev/types/-/types-0.22.7.tgz",
      "integrity": "sha512-mCVKQbcGTv6d6n9aHpYNp5U04HF+FMbpY083vqpJ6Folc805BB1Am02eubaW0J6nM+dSOu2dDgPY+kIjs75sAQ==",
      "license": "MIT",
      "engines": {
        "node": ">=14.0.0"
      },
      "funding": {
        "url": "https://github.com/sponsors/antfu"
      }
    },
    "node_modules/slidev-addon-rabbit/node_modules/theme-vitesse": {
      "version": "0.1.14",
      "resolved": "https://registry.npmjs.org/theme-vitesse/-/theme-vitesse-0.1.14.tgz",
      "integrity": "sha512-b5s+Zpfaw5+djoCJ9AEbcTbpiTlLsOvGM9oblDmmWRGWNqg9oXtEYO/uwubwx77novHBI6zNuwZRHKNlAIBo4A==",
      "license": "MIT",
      "engines": {
        "vscode": "^1.43.0"
      }
    },
```

The [Emoji One (Monotone)](https://icon-sets.iconify.design/emojione-monotone/) module doesn't look to be installed. When I install it:

```bash
npm install @iconify-json/emojione-monotone --save-dev
```

Everything works.

**Comment by kaakaa** [comment]
Thanks for reporting @jerdog. This would be fixed in v0.3.1.
